# Generated by Django 6.0.4 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(unique=True)),
                ('place_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('activities', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('budget_level', models.CharField(max_length=20)),
                ('tourist_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
