# Generated by Django 6.0.4 on 2026-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_place_created_at_place_featured_place_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='places/'),
        ),
    ]
