# Generated by Django 6.0.4 on 2026-07-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_place_image'),
        ('travel_app', '0003_emergencycontact_faq_hotel'),
    ]

    operations = [
    ]
