# Generated by Django 6.0.4 on 2026-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_merge_20260702_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
