# Generated by Django 6.0.3 on 2026-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
