# Generated by Django 6.0.3 on 2026-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_alter_hotel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('budget_level', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('tourist_type', models.CharField(max_length=50)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
