# Generated by Django 6.0.3 on 2026-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_recommendationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
