# Generated by Django 6.0.3 on 2026-07-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0010_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.place', to_field='place_id'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.CharField(max_length=50),
        ),
    ]
