# Generated by Django 6.0.3 on 2026-08-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0012_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
