# Generated by Django 6.0.6 on 2026-08-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0013_alter_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='tourist_type',
        ),
    ]
